<?php

return [
    'default_mode' => 'operations',
    'modes' => [
        'operations' => [
            'label' => 'Temizlik Operasyonları',
            'short_label' => 'Operasyon',
            'description' => 'Temizlik planlama, saha yönetimi ve operasyonel modüller',
            'theme' => [
                'class' => 'mode-operations',
                'nav_gradient' => 'from-primary-600 to-primary-700',
                'accent' => 'text-primary-100',
                'chip_bg' => 'bg-white/15',
                'chip_border' => 'border-white/20',
                'quick_action' => 'variant-operations',
                'context_bg' => 'bg-primary-900/10',
            ],
        ],
        'management' => [
            'label' => 'Yönetim Hizmetleri',
            'short_label' => 'Yönetim',
            'description' => 'Apartman, site ve sakin yönetimi modülleri',
            'theme' => [
                'class' => 'mode-management',
                'nav_gradient' => 'from-indigo-500 to-emerald-500',
                'accent' => 'text-emerald-100',
                'chip_bg' => 'bg-white/18',
                'chip_border' => 'border-white/30',
                'quick_action' => 'variant-management',
                'context_bg' => 'bg-emerald-900/15',
            ],
        ],
    ],
    'navigation' => [
        [
            'key' => 'dashboard',
            'label' => 'Ana',
            'icon' => 'fa-home',
            'url' => '/',
            'roles' => Roles::group('all'),
            'modes' => ['operations'],
        ],
        [
            'key' => 'calendar',
            'label' => 'Takvim',
            'icon' => 'fa-calendar',
            'url' => '/calendar',
            'roles' => Roles::group('nav.operations.core'),
            'modes' => ['operations'],
        ],
        [
            'key' => 'jobs',
            'label' => 'İşler',
            'icon' => 'fa-tasks',
            'url' => '/jobs',
            'roles' => Roles::group('nav.operations.core'),
            'modes' => ['operations'],
        ],
        [
            'key' => 'customers',
            'label' => 'Müşteriler',
            'icon' => 'fa-users',
            'url' => '/customers',
            'roles' => Roles::group('nav.operations.customers'),
            'modes' => ['operations'],
        ],
        [
            'key' => 'management',
            'label' => 'Yönetim',
            'icon' => 'fa-briefcase',
            'roles' => Roles::group('nav.operations.management'),
            'modes' => ['operations'],
            'children' => [
                [
                    'label' => 'Finans',
                    'icon' => 'fa-chart-line',
                    'url' => '/finance',
                    'roles' => Roles::group('nav.finance.core'),
                ],
                [
                    'label' => 'Randevular',
                    'icon' => 'fa-calendar-check',
                    'url' => '/appointments',
                    'roles' => Roles::group('nav.operations.core'),
                ],
                [
                    'label' => 'Sözleşmeler',
                    'icon' => 'fa-file-contract',
                    'url' => '/contracts',
                    'roles' => Roles::group('nav.finance.core'),
                ],
                [
                    'label' => 'Personel',
                    'icon' => 'fa-user-tie',
                    'url' => '/staff',
                    'roles' => Roles::group('nav.operations.management'),
                ],
            ],
        ],
        [
            'key' => 'operations',
            'label' => 'Operasyon',
            'icon' => 'fa-cogs',
            'roles' => Roles::group('nav.operations.management'),
            'modes' => ['operations'],
            'children' => [
                [
                    'label' => 'Periyodik',
                    'icon' => 'fa-redo',
                    'url' => '/recurring',
                    'roles' => Roles::group('nav.operations.management'),
                ],
                [
                    'label' => 'Hizmetler',
                    'icon' => 'fa-concierge-bell',
                    'url' => '/services',
                    'roles' => Roles::group('nav.operations.management'),
                ],
            ],
        ],
        [
            'key' => 'management-services',
            'label' => 'Yönetim Hizmetleri',
            'icon' => 'fa-city',
            'url' => '/management/dashboard',
            'roles' => Roles::group('nav.management.services'),
            'modes' => ['management'],
        ],
        [
            'key' => 'management-assets',
            'label' => 'Varlıklar',
            'icon' => 'fa-building',
            'roles' => Roles::group('nav.management.assets'),
            'modes' => ['management'],
            'children' => [
                ['label' => 'Binalar', 'icon' => 'fa-building', 'url' => '/buildings', 'roles' => Roles::group('nav.management.assets')],
                ['label' => 'Daireler', 'icon' => 'fa-home', 'url' => '/units', 'roles' => Roles::group('nav.management.assets.basic')],
                ['label' => 'Tesis & Rezervasyon', 'icon' => 'fa-door-open', 'url' => '/reservations', 'roles' => Roles::group('nav.management.assets.basic')],
            ],
        ],
        [
            'key' => 'management-finance',
            'label' => 'Finans',
            'icon' => 'fa-money-bill-wave',
            'roles' => Roles::group('nav.management.finance'),
            'modes' => ['management'],
            'children' => [
                ['label' => 'Aidat Yönetimi', 'icon' => 'fa-money-bill-wave', 'url' => '/management-fees', 'roles' => Roles::group('nav.management.finance')],
                ['label' => 'Gider Yönetimi', 'icon' => 'fa-receipt', 'url' => '/expenses', 'roles' => Roles::group('nav.management.finance')],
                ['label' => 'Finansal Raporlar', 'icon' => 'fa-chart-line', 'url' => '/building-reports/financial', 'roles' => Roles::group('nav.management.finance')],
            ],
        ],
        [
            'key' => 'management-communications',
            'label' => 'İletişim',
            'icon' => 'fa-comments',
            'roles' => Roles::group('nav.management.comms'),
            'modes' => ['management'],
            'children' => [
                ['label' => 'Doküman Merkezi', 'icon' => 'fa-file-alt', 'url' => '/documents', 'roles' => Roles::group('nav.management.assets.basic')],
                ['label' => 'Toplantılar', 'icon' => 'fa-people-group', 'url' => '/meetings', 'roles' => Roles::group('nav.management.assets.basic')],
                ['label' => 'Duyurular', 'icon' => 'fa-bullhorn', 'url' => '/announcements', 'roles' => Roles::group('nav.management.comms')],
                ['label' => 'Anketler', 'icon' => 'fa-poll', 'url' => '/surveys', 'roles' => Roles::group('nav.management.assets.basic')],
            ],
        ],
        [
            'key' => 'management-residents',
            'label' => 'Sakin Yönetimi',
            'icon' => 'fa-users',
            'roles' => Roles::group('nav.management.residents'),
            'modes' => ['management'],
            'children' => [
                ['label' => 'Sakinler', 'icon' => 'fa-users', 'url' => '/management/residents', 'roles' => Roles::group('nav.management.residents')],
                ['label' => 'Portal Durumu', 'icon' => 'fa-globe', 'url' => '/management/residents#portal-overview', 'roles' => Roles::group('nav.management.residents')],
                ['label' => 'Sakin Talepleri', 'icon' => 'fa-comments', 'url' => '/management/residents#resident-requests', 'roles' => Roles::group('nav.management.residents')],
            ],
        ],
        [
            'key' => 'analytics',
            'label' => 'Analitik',
            'icon' => 'fa-analytics',
            'url' => '/analytics',
            'roles' => Roles::group('nav.analytics'),
            'modes' => ['operations'],
        ],
        [
            'key' => 'reports',
            'label' => 'Raporlar',
            'icon' => 'fa-chart-bar',
            'roles' => Roles::group('nav.reports.core'),
            'modes' => ['operations'],
            'children' => [
                ['label' => 'Tüm Raporlar', 'icon' => 'fa-list', 'url' => '/reports', 'roles' => Roles::group('nav.reports.core')],
                ['label' => 'Finansal Rapor', 'icon' => 'fa-money-bill-wave', 'url' => '/reports/financial', 'roles' => Roles::group('nav.reports.core')],
                ['label' => 'İş Raporu', 'icon' => 'fa-tasks', 'url' => '/reports/jobs', 'roles' => Roles::group('nav.reports.jobs')],
                ['label' => 'Müşteri Raporu', 'icon' => 'fa-users', 'url' => '/reports/customers', 'roles' => Roles::group('nav.reports.customers')],
                ['label' => 'Hizmet Analizi', 'icon' => 'fa-concierge-bell', 'url' => '/reports/services', 'roles' => Roles::group('nav.reports.jobs')],
                ['label' => 'Veri Dışa Aktarma', 'icon' => 'fa-download', 'url' => '/export', 'roles' => Roles::group('nav.reports.export')],
            ],
        ],
        [
            'key' => 'settings',
            'label' => 'Ayarlar',
            'icon' => 'fa-cog',
            'roles' => Roles::group('nav.settings.admin'),
            'modes' => ['operations', 'management'],
            'children' => [
                ['label' => 'Profil', 'icon' => 'fa-user', 'url' => '/settings/profile', 'roles' => Roles::group('all')],
                ['label' => 'Güvenlik', 'icon' => 'fa-shield-alt', 'url' => '/settings/security', 'roles' => Roles::group('all')],
                ['label' => 'Güvenlik Paneli', 'icon' => 'fa-chart-line', 'url' => '/security/dashboard', 'roles' => Roles::group('nav.settings.admin')], // ROUND 5: Security Dashboard
                ['label' => 'Kullanıcılar', 'icon' => 'fa-users', 'url' => '/settings/users', 'roles' => Roles::group('nav.settings.admin')],
                ['label' => 'İzleme', 'icon' => 'fa-chart-line', 'url' => '/settings/monitoring', 'roles' => Roles::group('nav.settings.admin')],
                ['label' => 'Loglar', 'icon' => 'fa-file-alt', 'url' => '/settings/logs', 'roles' => Roles::group('nav.settings.admin')],
                ['label' => 'Yedekleme', 'icon' => 'fa-database', 'url' => '/settings/backup', 'roles' => Roles::group('nav.settings.admin')],
                ['label' => 'Email Logları', 'icon' => 'fa-envelope', 'url' => '/admin/emails/logs', 'roles' => Roles::group('nav.settings.admin')],
                ['label' => 'Email Queue', 'icon' => 'fa-list', 'url' => '/admin/emails/queue', 'roles' => Roles::group('nav.settings.admin')],
            ],
        ],
    ],
    'quick_actions' => [
        [
            'label' => 'Yeni İş',
            'icon' => 'fa-plus-circle',
            'url' => '/jobs/new',
            'roles' => Roles::group('quick.operations.core'),
            'modes' => ['operations'],
        ],
        [
            'label' => 'Periyodik İş',
            'icon' => 'fa-redo',
            'url' => '/recurring/new',
            'roles' => Roles::group('quick.operations.core'),
            'modes' => ['operations'],
        ],
        [
            'label' => 'Yeni Finans',
            'icon' => 'fa-credit-card',
            'url' => '/finance/new',
            'roles' => Roles::group('quick.finance'),
            'modes' => ['operations', 'management'],
        ],
        [
            'label' => 'Aidat Oluştur',
            'icon' => 'fa-money-check-alt',
            'url' => '/management-fees/generate',
            'roles' => Roles::group('quick.management.finance'),
            'modes' => ['management'],
        ],
        [
            'label' => 'Toplantı Planla',
            'icon' => 'fa-calendar-plus',
            'url' => '/meetings/create',
            'roles' => Roles::group('quick.management.core'),
            'modes' => ['management'],
        ],
        [
            'label' => 'Yeni Duyuru',
            'icon' => 'fa-bullhorn',
            'url' => '/announcements/create',
            'roles' => Roles::group('quick.management.communications'),
            'modes' => ['management'],
        ],
        [
            'label' => 'Sakin Portalı',
            'icon' => 'fa-user-group',
            'url' => '/management/residents#portal-actions',
            'roles' => Roles::group('quick.management.communications'),
            'modes' => ['management'],
        ],
    ],
    'context_links' => [
        'operations' => [
            'calendar' => ['Takvim', 'fa-calendar', '/calendar'],
            'jobs' => ['İşler', 'fa-tasks', '/jobs'],
            'recurring' => ['Periyodik İşler', 'fa-redo', '/recurring'],
            'services' => ['Hizmetler', 'fa-concierge-bell', '/services'],
        ],
        'management' => [
            'management' => ['Dashboard', 'fa-gauge-high', '/management/dashboard'],
            'buildings' => ['Binalar', 'fa-building', '/buildings'],
            'units' => ['Daireler', 'fa-home', '/units'],
            'management-fees' => ['Aidatlar', 'fa-money-bill', '/management-fees'],
            'expenses' => ['Giderler', 'fa-receipt', '/expenses'],
            'meetings' => ['Toplantılar', 'fa-people-group', '/meetings'],
            'reservations' => ['Rezervasyonlar', 'fa-door-open', '/reservations'],
            'announcements' => ['Duyurular', 'fa-bullhorn', '/announcements'],
            'surveys' => ['Anketler', 'fa-poll', '/surveys'],
            'residents' => [
                'overview' => ['Sakin Yönetimi', 'fa-users', '/management/residents'],
                'portal' => ['Portal Durumu', 'fa-globe', '/management/residents#portal-overview'],
                'requests' => ['Sakin Talepleri', 'fa-comments', '/management/residents#resident-requests'],
            ],
        ],
    ],
];

