<?php

return [
    'roles' => [
        'SUPERADMIN' => [
            'label' => 'Sistem Yöneticisi',
            'description' => 'Platformun tamamında tam yetkiye sahip global yönetici.',
            'scope' => 'staff',
            'hierarchy' => 100,
            'capabilities' => [
                'system.*',
                'operations.*',
                'management.*',
                'finance.*',
                'security.*',
                'api.*',
                'tenant.switch',
            ],
        ],
        'ADMIN' => [
            'label' => 'Operasyon Yöneticisi',
            'description' => 'Operasyon ve yönetim modüllerinde tam yönetim ve onay yetkisi.',
            'scope' => 'staff',
            'hierarchy' => 90,
            'capabilities' => [
                'operations.plan',
                'operations.assign',
                'customers.manage',
                'customers.view',
                'customers.create',
                'customers.edit',
                'customers.delete',
                'customers.export',
                'jobs.view',
                'jobs.create',
                'jobs.edit',
                'jobs.delete',
                'management.access',
                'finance.authorize',
                'finance.export',
                'reports.view',
                'reports.financial',
                'reports.jobs',
                'reports.customers',
                'reports.export',
                'api.access',
                'tenant.switch',
            ],
        ],
        'OPERATOR' => [
            'label' => 'Operasyon Uzmanı',
            'description' => 'Saha planlama, iş yönetimi ve müşteri iletişimini yürütür.',
            'scope' => 'staff',
            'hierarchy' => 70,
            'capabilities' => [
                'operations.plan',
                'operations.execute',
                'customers.view',
                'jobs.view',
                'jobs.create',
                'jobs.edit',
                'reports.jobs',
                'api.jobs',
            ],
        ],
        'SITE_MANAGER' => [
            'label' => 'Site Yöneticisi',
            'description' => 'Apartman/site finansı, sakin iletişimi ve portal yönetimi.',
            'scope' => 'staff',
            'hierarchy' => 65,
            'capabilities' => [
                'management.assets',
                'management.residents',
                'management.finance',
                'communications.manage',
                'api.customers',
            ],
        ],
        'FINANCE' => [
            'label' => 'Finans Uzmanı',
            'description' => 'Tahsilat, gider ve finansal raporlamadan sorumlu.',
            'scope' => 'staff',
            'hierarchy' => 60,
            'capabilities' => [
                'finance.collect',
                'finance.report',
                'finance.export',
                'reports.view',
                'reports.financial',
                'reports.customers',
                'reports.export',
                'customers.view',
                'api.customers',
            ],
        ],
        'SUPPORT' => [
            'label' => 'Destek Uzmanı',
            'description' => 'Saha ve sakin iletişimi, bildirimler ve portal destek süreçleri.',
            'scope' => 'staff',
            'hierarchy' => 55,
            'capabilities' => [
                'communications.manage',
                'residents.support',
                'customers.view',
                'reports.customers',
                'api.access',
            ],
        ],
        'MANAGEMENT' => [
            'label' => 'Yönetim Analisti',
            'description' => 'Yönetim paneli ve analitik modüller için salt-okunur erişim.',
            'scope' => 'staff',
            'hierarchy' => 50,
            'capabilities' => [
                'analytics.view',
                'reports.view',
                'reports.financial',
                'reports.jobs',
                'reports.customers',
            ],
        ],
        'RESIDENT_OWNER' => [
            'label' => 'Kat Maliki',
            'description' => 'Aidat ve sakin talepleri üzerinde tam görünürlüğe sahip apartman sakini.',
            'scope' => 'resident_portal',
            'hierarchy' => 35,
            'capabilities' => [
                'resident.dashboard',
                'resident.finance',
                'resident.requests',
            ],
        ],
        'RESIDENT_TENANT' => [
            'label' => 'Kiracı',
            'description' => 'Talep ve bildirim takibi yapabilen sakin profili.',
            'scope' => 'resident_portal',
            'hierarchy' => 25,
            'capabilities' => [
                'resident.dashboard',
                'resident.requests',
            ],
        ],
        'RESIDENT_BOARD' => [
            'label' => 'Yönetim Kurulu',
            'description' => 'Toplantı/duyuru yönetimi için yetkili sakin.',
            'scope' => 'resident_portal',
            'hierarchy' => 33,
            'capabilities' => [
                'resident.dashboard',
                'resident.management',
            ],
        ],
        'RESIDENT_GUEST' => [
            'label' => 'Misafir',
            'description' => 'Sınırlı erişimli ziyaretçi hesabı.',
            'scope' => 'resident_portal',
            'hierarchy' => 10,
            'capabilities' => [
                'resident.dashboard',
            ],
        ],
        'CUSTOMER_STANDARD' => [
            'label' => 'Müşteri',
            'description' => 'Hizmet durumlarını takip eden standart müşteri hesabı.',
            'scope' => 'customer_portal',
            'hierarchy' => 25,
            'capabilities' => [
                'portal.dashboard',
                'portal.jobs',
            ],
        ],
        'CUSTOMER_VIP' => [
            'label' => 'VIP Müşteri',
            'description' => 'Özel rapor ve öncelikli destek erişimi olan müşteri.',
            'scope' => 'customer_portal',
            'hierarchy' => 35,
            'capabilities' => [
                'portal.dashboard',
                'portal.jobs',
                'portal.invoices',
            ],
        ],
        'CUSTOMER_CORPORATE' => [
            'label' => 'Kurumsal',
            'description' => 'Çok lokasyonlu kurumsal müşteriler için rol.',
            'scope' => 'customer_portal',
            'hierarchy' => 40,
            'capabilities' => [
                'portal.dashboard',
                'portal.jobs',
                'portal.invoices',
                'portal.analytics',
            ],
        ],
    ],
    'groups' => [
        'all' => ['*'],

        // Navigation groupings
        'nav.operations.core' => ['ADMIN', 'OPERATOR', 'SUPPORT'],
        'nav.operations.management' => ['ADMIN', 'OPERATOR'],
        'nav.operations.customers' => ['ADMIN', 'OPERATOR', 'FINANCE', 'SUPPORT'],
        'nav.finance.core' => ['ADMIN', 'FINANCE'],
        'nav.management.services' => ['ADMIN', 'SITE_MANAGER', 'FINANCE', 'OPERATOR'],
        'nav.management.assets' => ['ADMIN', 'SITE_MANAGER', 'OPERATOR'],
        'nav.management.assets.basic' => ['ADMIN', 'SITE_MANAGER'],
        'nav.management.finance' => ['ADMIN', 'SITE_MANAGER', 'FINANCE'],
        'nav.management.comms' => ['ADMIN', 'SITE_MANAGER', 'SUPPORT'],
        'nav.management.residents' => ['ADMIN', 'SITE_MANAGER', 'SUPPORT'],
        'nav.analytics' => ['ADMIN', 'MANAGEMENT', 'FINANCE'],
        'nav.reports.core' => ['ADMIN', 'FINANCE', 'SITE_MANAGER', 'SUPERADMIN', 'OPERATOR'],
        'nav.reports.jobs' => ['ADMIN', 'OPERATOR'],
        'nav.reports.customers' => ['ADMIN', 'FINANCE', 'SUPPORT'],
        'nav.reports.export' => ['ADMIN', 'FINANCE'],
        'nav.settings.admin' => ['ADMIN', 'SUPERADMIN'],
        'nav.settings.public' => ['*'],

        // Quick actions / shortcuts
        'quick.operations.core' => ['ADMIN', 'OPERATOR'],
        'quick.finance' => ['ADMIN', 'FINANCE'],
        'quick.management.finance' => ['ADMIN', 'SITE_MANAGER', 'FINANCE'],
        'quick.management.core' => ['ADMIN', 'SITE_MANAGER'],
        'quick.management.communications' => ['ADMIN', 'SITE_MANAGER', 'SUPPORT'],

        // API and service integrations
        'api.access' => ['ADMIN', 'SUPERADMIN', 'OPERATOR', 'SITE_MANAGER', 'SUPPORT', 'FINANCE'],
        'api.jobs.modify' => ['ADMIN', 'SUPERADMIN', 'OPERATOR'],
        'api.customers.read' => ['ADMIN', 'SUPERADMIN', 'FINANCE', 'SITE_MANAGER', 'SUPPORT'],
    ],
];

