<?php
$scopeOptions = $scope_labels ?? [
    'staff' => 'Personel',
    'resident_portal' => 'Sakin Portalı',
    'customer_portal' => 'Müşteri Portalı',
];
?>

<!-- Breadcrumb will be auto-generated by base.php -->

<!-- Page Header -->
<div class="mb-8">
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-3xl font-bold text-gray-900 dark:text-white">
                <i class="fas fa-user-shield mr-3"></i>
                Yeni Rol Oluştur
            </h1>
            <p class="mt-2 text-gray-600 dark:text-gray-400">
                Belirli izinler ve hiyerarşi seviyesiyle yeni bir rol oluşturun
            </p>
        </div>

        <!-- Scope -->
        <div>
            <label for="scope" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Kapsam <span class="text-red-500">*</span>
            </label>
            <select id="scope"
                    name="scope"
                    class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white">
                <?php foreach ($scopeOptions as $value => $label): ?>
                    <option value="<?= e($value) ?>"
                            <?= (($_POST['scope'] ?? 'staff') === $value) ? 'selected' : '' ?>>
                        <?= e($label) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
                Rolün hangi platformda kullanılacağını seçin.
            </p>
        </div>
        <div class="flex space-x-3">
            <a href="<?= base_url('/admin/roles') ?>" 
               class="inline-flex items-center px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white font-medium rounded-lg transition-colors duration-200">
                <i class="fas fa-arrow-left mr-2"></i>
                Geri
            </a>
        </div>
    </div>
</div>

<!-- Flash Messages -->
<?php if (has_flash('error')): ?>
    <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 mb-6 rounded-lg" role="alert">
        <div class="flex items-center">
            <i class="fas fa-exclamation-circle mr-2"></i>
            <div>
                <?php if (is_array(get_flash('error'))): ?>
                    <ul class="list-disc list-inside">
                        <?php foreach (get_flash('error') as $error): ?>
                            <li><?= e($error) ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php else: ?>
                    <?= htmlspecialchars(get_flash('error') ?? '') ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<!-- Create Form -->
<div class="bg-white dark:bg-gray-800 rounded-xl shadow-soft border border-gray-200 dark:border-gray-700 p-6">
    <form method="POST" action="<?= base_url('/admin/roles/create') ?>" class="space-y-8">
        <?= CSRF::field() ?>
        
        <!-- Role Name -->
        <div>
            <label for="name" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Rol Adı <span class="text-red-500">*</span>
            </label>
            <input type="text" 
                   id="name" 
                   name="name" 
                   required 
                   class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white"
                   placeholder="örn: TAKIM_LIDERI"
                   value="<?= htmlspecialchars($_POST['name'] ?? '') ?>">
            <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
                Büyük harf ve alt çizgi kullanın (örn: TAKIM_LIDERI, SATIS_YONETICISI)
            </p>
        </div>

        <!-- Description -->
        <div>
            <label for="description" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Açıklama <span class="text-red-500">*</span>
            </label>
            <textarea id="description" 
                      name="description" 
                      required 
                      rows="3" 
                      class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white"
                      placeholder="Rolün amacını ve sorumluluklarını açıklayın"><?= htmlspecialchars($_POST['description'] ?? '') ?></textarea>
        </div>

        <!-- Hierarchy Level -->
        <div>
            <label for="hierarchy_level" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Hiyerarşi Seviyesi <span class="text-red-500">*</span>
            </label>
            <input type="number" 
                   id="hierarchy_level" 
                   name="hierarchy_level" 
                   required 
                   min="0" 
                   max="100" 
                   value="<?= htmlspecialchars($_POST['hierarchy_level'] ?? '50') ?>"
                   class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white">
            <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
                0-100 (Daha yüksek sayı = Daha yüksek yetki. SUPER_ADMIN=100, ADMIN=80, MANAGER=60, USER=20)
            </p>
        </div>

        <!-- Parent Role -->
        <div>
            <label for="parent_role" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Ana Rol (İsteğe Bağlı)
            </label>
            <select id="parent_role" 
                    name="parent_role" 
                    class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white">
                <option value="">-- Yok --</option>
                <?php if (isset($parent_roles)): ?>
                    <?php foreach ($parent_roles as $role): ?>
                        <option value="<?= e($role['name']) ?>" 
                                <?= (($_POST['parent_role'] ?? '') === $role['name']) ? 'selected' : '' ?>>
                            <?= e($role['name']) ?> (Seviye <?= $role['hierarchy_level'] ?>)
                        </option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
            <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
                Bir ana rolden izinleri devralın
            </p>
        </div>

        <!-- System Role -->
        <div class="flex items-center">
            <input type="checkbox" 
                   id="is_system_role" 
                   name="is_system_role" 
                   value="1"
                   <?= isset($_POST['is_system_role']) ? 'checked' : '' ?>
                   class="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700">
            <label for="is_system_role" class="ml-2 text-sm text-gray-700 dark:text-gray-300">
                Sistem Rolü (Kullanıcılar tarafından silinemez)
            </label>
        </div>

        <!-- Action Buttons -->
        <div class="flex items-center justify-between pt-6 border-t border-gray-200 dark:border-gray-700">
            <a href="<?= base_url('/admin/roles') ?>" 
               class="px-6 py-2 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 transition">
                <i class="fas fa-times mr-2"></i>İptal
            </a>
            <button type="submit" 
                    class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition">
                <i class="fas fa-save mr-2"></i>Rol Oluştur
            </button>
        </div>
    </form>
</div>

<!-- Help Section -->
<div class="mt-6 bg-blue-50 dark:bg-blue-900/20 border-l-4 border-blue-500 p-4 rounded-lg">
    <div class="flex items-start">
        <i class="fas fa-info-circle text-blue-500 mr-3 mt-1"></i>
        <div class="text-sm text-blue-700 dark:text-blue-200">
            <p class="font-semibold mb-2">Rol Oluşturma Kılavuzu:</p>
            <ul class="list-disc list-inside space-y-1">
                <li>Rolün amacını açıkça belirten açıklayıcı isimler kullanın</li>
                <li>Yetki yapısını oluşturmak için uygun hiyerarşi seviyelerini ayarlayın</li>
                <li>Temel izinleri devralmak için ana roller kullanmayı düşünün</li>
                <li>Yalnızca kritik, yerleşik roller için sistem rolü olarak işaretleyin</li>
            </ul>
        </div>
    </div>
</div>

